//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidReleaseCandidateGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidReleaseCandidateGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a zipalign -v -p 4 {unaligned} {aligned}.
        /// </summary>
        public static string alignCommand {
            get {
                return ResourceManager.GetString("alignCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\Local\Android\Sdk\build-tools\27.0.3.
        /// </summary>
        public static string androidToolsPath {
            get {
                return ResourceManager.GetString("androidToolsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\POC_REPOS\Metadata\POCmobile_android\keystore-java-7-sha1.keystore.
        /// </summary>
        public static string keyStoreFileMobile {
            get {
                return ResourceManager.GetString("keyStoreFileMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\POC_REPOS\Metadata\POC_android\keystore_sha1.keystore.
        /// </summary>
        public static string keyStoreFileTablet {
            get {
                return ResourceManager.GetString("keyStoreFileTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mPoc\mPOC\build\outputs\apk\.
        /// </summary>
        public static string mobileFileLocation {
            get {
                return ResourceManager.GetString("mobileFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\POC_REPOS\mPoc.
        /// </summary>
        public static string mPocRootFolderPath {
            get {
                return ResourceManager.GetString("mPocRootFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\POC_REPOS\mPoc_tablet_3.
        /// </summary>
        public static string pocRootFolderPath {
            get {
                return ResourceManager.GetString("pocRootFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D:\POC_REPOS\.
        /// </summary>
        public static string routeToLocalRepositoryFolder {
            get {
                return ResourceManager.GetString("routeToLocalRepositoryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sha512sum {signedAligned} &gt; {sha512}.
        /// </summary>
        public static string sha512Command {
            get {
                return ResourceManager.GetString("sha512Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apksigner sign --ks {keystore_file_name} --ks-pass env:{envVar} --out {signed} {aligned}.
        /// </summary>
        public static string signCommand {
            get {
                return ResourceManager.GetString("signCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mPoc_tablet_3\poc\build\outputs\apk\.
        /// </summary>
        public static string tabletFileLocation {
            get {
                return ResourceManager.GetString("tabletFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apksigner verify --verbose {outputLocation}{signedAligned}.
        /// </summary>
        public static string verifySignatureCommand {
            get {
                return ResourceManager.GetString("verifySignatureCommand", resourceCulture);
            }
        }
    }
}
